name: Honda
title: Honda
description: honda dealership in City
markdown: redcarpet
highlighter: rouge # or pygments or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

baseurl: /honda

gems:
  - jekyll-redirect-from
